"""sort for category tag

Revision ID: 84c52219e81d
Revises: 60efac315404
Create Date: 2018-05-01 15:09:32.510512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c52219e81d'
down_revision = '60efac315404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sort', sa.Integer(), nullable=True))
    op.add_column('tag', sa.Column('sort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'sort')
    op.drop_column('category', 'sort')
    # ### end Alembic commands ###
