"""category add slug

Revision ID: b17252e2d914
Revises: e63549cd0828
Create Date: 2018-04-29 23:32:38.464939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17252e2d914'
down_revision = 'e63549cd0828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
