"""image, color in category

Revision ID: b7ca74152ac6
Revises: 84c52219e81d
Create Date: 2018-05-01 15:16:17.819831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ca74152ac6'
down_revision = '84c52219e81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sa.String(length=128), nullable=True))
    op.add_column('category', sa.Column('title_background', sa.String(length=7), nullable=True))
    op.add_column('category', sa.Column('title_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'title_color')
    op.drop_column('category', 'title_background')
    op.drop_column('category', 'image')
    # ### end Alembic commands ###
